spring.application.name=crm-service

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:xenocrm
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=${GEMINI_API_KEY:your-api-key-here}
gemini.model.name=gemini-2.5-flash

# Channel Service URL
channel.service.url=${CHANNEL_SERVICE_URL}